strings:
  - name: "6 (E2)"
    open_freq: 82.2
    measurements:
      1: 87.4
      3: 98.0
      5: 109.9
      7: 123.3
      9: 138.6
      12: 164.9
  - name: "5 (A2)"
    open_freq: 109.8
    measurements:
      1: 116.7
      3: 131.0
      5: 147.0
      7: 164.6
      9: 185.0
      12: 220.0
  - name: "4 (D3)"
    open_freq: 147.3
    measurements:
      1: 156.3
      3: 175.5
      5: 197.1
      7: 221.1
      9: 248.0
      12: 295.2
  - name: "3 (G3)"
    open_freq: 196.2
    measurements:
      1: 208.3
      3: 233.6
      5: 262.5
      7: 294.0
      9: 329.8
      12: 392.4
  - name: "2 (B3)"
    open_freq: 247.2
    measurements:
      1: 262.6
      3: 294.6
      5: 330.8
      7: 371.1
      9: 416.4
      12: 496.0
  - name: "1 (E4)"
    open_freq: 330.1
    measurements:
      1: 350.3
      3: 393.5
      5: 441.4
      7: 495.4
      9: 555.6
      12: 661.9
